#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 15 13:55:26 2024

@author: williamchung
"""

def QuickSort(array, start, end):
    if start >= end:
        return
    
    pivot = array[start]
    left = start + 1
    right = end
    
    while left <= right:
        while left <= end and array[left] <= pivot:
            left += 1
        while right > start and array[right] >= pivot:
            right -= 1
        if left < right:
            array[left], array[right] = array[right], array[left]

    array[start], array[right] = array[right], array[start]

#排序過程
    print("排序過程中的狀態：", array)
 
#遞迴    
    QuickSort(array, start, right - 1)
    QuickSort(array, right + 1, end)

arr = [33, 67, 8, 13, 54, 119, 3, 84, 25, 41]
print("原始列表：", arr)
QuickSort(arr, 0, len(arr) - 1)
print("排序後：", arr)
